### ISSUE TITLE
Quick Fix: Extra / 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/sinatra-multiple-controllers#12]
The Orders Controller sentence might have an extra /  at the end  OR the Products Controller sentence might need an /     .     
**********************

Products Controller
You can imagine a controller ProductsController, defined in app/controllers/products_controller.rb.Orders Controller

Orders Controller
Similarly, we'd have OrdersController defined in app/controllers/orders_controller.rb/

**Comment by drakeltheryuujin** [comment]
Thanks for your contribution!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
