### ISSUE TITLE
Unclear:   order_controller.rb has an / 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/sinatra-multiple-controllers#13]
Hi there. 

Not sure if the / is needed at the end of this first sentence. I could not figure the difference out and why one controller would not have the / .  
When comparing the ProductsController, defined in app/controllers/products_controller.rb. there's no / after the rb
**********
HERE'S THE TEXT:  

Similarly, we'd have OrdersController defined in app/controllers/orders_controller.rb/

class OrdersController < Sinatra::Base
 
  get '/orders' do
    "Order Index"
  end
 
  get '/orders/:id' do
    "Order #{params[:id]} Show"
  end
 
end

**Comment by Sdcrouse** [comment]
I'm guessing that's a typo. There's a similar sentence describing the ProductsController class above it, but there's no / at the end of it.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
