### ISSUE TITLE
Incorrect delete action in RESTful table

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/sinatra-multiple-controllers#15]
Shows a DELETE being a post request to item/id/delete instead of a delete request to item/id. This is inconsistent with other parts of the curriculum which specify the second (correct) way to delete a database item.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
